name: Update flake lock
on:
    workflow_dispatch: # allows manual triggering

    schedule:
        - cron: "0 0 * * 0" # runs weekly on Sunday at 00:00
jobs:
    lockfile:
        runs-on: ubuntu-latest
        outputs: 
            pr-number: ${{ steps.update.outputs.pull-request-number }}
        permissions:
            contents: write # to push the branch for the PR
            pull-requests: write # to open the PR

        steps:
            - name: Checkout repository
              uses: actions/checkout@v5
            - name: Install Nix
              uses: DeterminateSystems/nix-installer-action@main
            - name: Update flake.lock
              id: update
              uses: DeterminateSystems/update-flake-lock@main
              with:
                  pr-title: "Update flake.lock" # Title of PR to be created
                  pr-labels: | # Labels to be set on the PR
                      dependencies
                      automated
            - name: Automerge update PR
              if: ${{ steps.update.outputs.pull-request-number != '' }}
              uses: peter-evans/enable-pull-request-automerge@v3
              with:
                  token: ${{ secrets.ACTIONS_PAT }}
                  pull-request-number: ${{ steps.update.outputs.pull-request-number }}
                  merge-method: squash
            
